config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'vehicles#index'

  resources :vehicles do
    resources :locations, only: [:create]
  end

  namespace :api , defaults: {format: :json} do
    namespace :v1 do
      resources :vehicles, only: [:show, :create],:path => 'gps' do
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :vehicle, optional: true

  #geocode
  reverse_geocoded_by :latitude, :longitude
 # auto-fetch address
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  has_many :locations

  validates :vehicle_identifier, uniqueness: true

  accepts_nested_attributes_for :locations, allow_destroy: true

  reverse_geocoded_by :latitude, :longitude

end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/api/v1/vehicles_controller.rb
class Api::V1::VehiclesController < Api::V1::ApplicationController

  before_action :set_action, only: [:show]

  def create
    @vehicle = Vehicle.new(require_params)
    respond_to do |format|
      if @vehicle.save
        VehicleWorker.perform_async(@vehicle.id)
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  private

  def set_action
    @vehicle = Vehicle.find(params[:id])
  end

  def require_params
    params.require(:vehicle).permit(:id, :vehicle_identifier, :sent_at,
    locations_attributes:[:vehicle_id, :longitude,:latitude])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_vehicle
  def new
    @location = @vehicle.locations.build
  end

  def create
    @location = @vehicle.locations.build(require_params)
    @vehicle.id = @location.vehicle_id
    respond_to do |format|
      if @location.save
        format.html { redirect_to @vehicle, notice: 'Vehículo creado con éxito.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def require_params
    params.require(:location).permit(:vehicle_id, :longitude,:latitude)
  end

  def set_vehicle
    @vehicle = Vehicle.find params[:vehicle_id]
  end

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

   before_action :set_action, only: [:show]

  def index
    @vehicles = Vehicle.all
    @hash = Gmaps4rails.build_markers(@vehicles) do |vehicle, marker|
      vehicle_path = view_context.link_to vehicle.vehicle_identifier, vehicle_path(vehicle)
      marker.infowindow render_to_string(partial: "vehicles/infowindows", locals: {vehicle: vehicle, vehicle_path: vehicle_path})
      marker.lat vehicle.locations.last.latitude
      marker.lng vehicle.locations.last.longitude
      marker.picture({
        "url" => view_context.image_path("http://yava.ro/icons/car.png"),
        "width" => 32,
        "height" => 37
      })
    end
  end

  def new
    @vehicle = Vehicle.new
    @vehicle.locations.build
  end

  def create
    @vehicle = Vehicle.new(require_params)
    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehículo creado con éxito.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @hash = Gmaps4rails.build_markers(@vehicle) do |vehicle, marker|
      marker.lat vehicle.locations.last.latitude
      marker.lng vehicle.locations.last.longitude
      marker.infowindow render_to_string(partial: "vehicles/infowindows", locals: {vehicle: vehicle, vehicles_path: vehicles_path})
      marker.picture({
        "url" => view_context.image_path("http://yava.ro/icons/car.png"),
        "width" => 32,
        "height" => 37
      })
    end
  end

  private

  def set_action
    @vehicle = Vehicle.find(params[:id])
  end

  def require_params
    params.require(:vehicle).permit(:id, :vehicle_identifier, :sent_at,
    locations_attributes:[:vehicle_id, :longitude,:latitude])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeetrackGps</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="//maps.google.com/maps/api/js?key=AIzaSyCuT-SKxU4v0gFZpt04hMKi15-DN8hH8sU"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vehicles/_infowindows.html.erb
<ul>
  <li><b>Vehículo patente: </b><%= link_to "#{vehicle.vehicle_identifier}", vehicle_path(vehicle) %></li>
  <li><b>Enviado: </b> <%=vehicle.sent_at%></li>
  <li><b>Latitud: </b> <%=vehicle.locations.last.latitude%></li>
  <li><b>Longitud: </b> <%=vehicle.locations.last.longitude%></li>
</ul>

app/views/vehicles/index.html.erb
<div class="container-fluid">
  <div id='indexmap' data-raw='<%=raw @hash.to_json %>'style='width: 800px;'>
    <div id="map" style='width: 1100px; height: 400px;'></div>
  </div></br>
  <table class="table detail_table">
    <thead>
      <tr>
        <th>id</th>
        <th>Identificador del vehículo</th>
        <th>Enviado</th>
        <th>Latitud</th>
        <th>Longitud</th>
        <th>Detalle</th>
      </tr>
    </thead>
    <tbody>
      <% @vehicles.each do |v| %>
        <tr>
          <td><%= v.id %></td>
          <td><%= v.vehicle_identifier %></td>
          <td><%= v.sent_at  %></td>
          <% v.locations.order('created_at desc').take(1).each do |l| %>
            <td><%= l.latitude %></td>
            <td><%= l.longitude  %></td>
          <% end %>
          <td><%= link_to "Mostrar", v  %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Nuevo vehículo', new_vehicle_path, class:"btn btn-primary" %>
</div>


<script>
	$(function(){ Vehicle.init('index',$('#indexmap').data('raw'));});
</script>

app/views/vehicles/new.html.erb
<div class="container-fluid">
  <%= form_for @vehicle do |f| %>
    <% if @vehicle.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

        <ul>
        <% @vehicle.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="page-header">
      <h1>Crear nuevo <small>vehículo</small></h1>
    </div>

    <div class="form-group row ">
      <div class="col-sm-12"></br>
        <div class="form-group">
          <%= f.label "Identificador del vehículo" %></br>
          <%= f.text_field :vehicle_identifier %>
        </div>
        <div class="form-group">
          <%= f.label "Enviado" %></br>
          <%= f.text_field :sent_at %>
        </div>

        <%= f.fields_for :locations do |l| %>
          <div class="form-group">
            <%= l.label "Latitud" %></br>
            <%= l.text_field :latitude %>
          </div>

          <div class="form-group">
            <%= l.label "Longitud" %></br>
            <%= l.text_field :longitude %>
          </div>

          <div class="actions">
            <%= f.submit "Crear vehículo", class:"btn btn-primary"%>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/vehicles/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-3">
      <div class="panel-heading"><b><u>Vehículo</u></b></div></br>
        <div class="font-size_detail">
          <p><b>Identificador del vehículo:</b> <%= @vehicle.vehicle_identifier %></p>
          <p><b>Enviado:</b> <%= @vehicle.sent_at %></p>
          <% @vehicle.locations.each_with_index do |a,index| %>
            <% if index == @vehicle.locations.size - 1 %>
              <p><b>Latitud:</b> <%= a.latitude %></p>
              <p><b>Longitud:</b> <%= a.longitude %></p>
            <% end %>
          <% end %>
        </div>
    </div>
    <div class="col-4">
      <div class="contain_table">
        <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading"><b><u>Historial de coordenadas</u></b></div></br>
          <table class="table detail_table">
            <thead>
              <tr>
                <th>Latitud</th>
                <th>Longitud</th>
              </tr>
            </thead>
            <tbody>
              <% @vehicle.locations.order('created_at desc').each do |l| %>
                <tr>
                  <td><%= l.latitude %></td>
                  <td><%= l.longitude  %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="panel panel-default">
        <div class="panel-heading"><b><u>Agregar nueva coordenada</u></b></div></br>
        <%= form_for [@vehicle, @vehicle.locations.build], remote: true do |f| %>
          <div class="form-group">
            <b><%= f.label "Latitud:" %></b></br>
            <%= f.text_field :latitude %>
          </div>
          <div class="form-group">
            <b> <%= f.label "Longitud:" %></b></br>
            <%= f.text_field :longitude %>
          </div>
          <div class="actions">
            <%= f.submit "Ingresar coordenada", class:"btn btn-primary"%>
          </div>
        <% end %>
      </div>
    </div>
  </div></br>

  <div id='showmap' data-raw='<%=raw @hash.to_json %>' style='width: 100%;'>
    <div id="map" style='width: 1100px; height: 400px;'></div>
  </div>

  <%= link_to 'Regresar', vehicles_path %>
</div>

<script>
	$(function(){ Vehicle.init('show',$('#showmap').data('raw'));});
</script>